spring:
  application:
    name: films-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/films?serverTimezone=UTC
    username: root
    password: secret
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server: 
  port: 8001
# Config de el servidor  
eureka: 
  client:
    serviceUrl:
      # Direccion a la que se conecta el microservicio con eureka
      defaultZone: http://localhost:8761/eureka
